export { default as Login }     from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Users }     from './Users'
export { default as UserInfo }  from './UserInfo'
export { default as Sales }     from './Sales'
export { default as Inventory } from './Inventory'
export { default as Register }  from './Register'